[package]
name = "maze"
version = "0.1.0"
authors = ["mahmoudFarouk <mahmoud.farouk@femto15.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
